--=================Create Database===================
USE [master] 

CREATE DATABASE Store
 ON  PRIMARY 
( NAME = N'Store', FILENAME = N'D:\DATABASE\Store.mdf' , SIZE = 10240KB ,MAXSIZE= UNLIMITED, FILEGROWTH = 65536KB ),
 FILEGROUP FG_FILESTREAM CONTAINS FILESTREAM 
( NAME = N'StoreFS', FILENAME = N'D:\DATABASE\Store_FSG')
 LOG ON 
( NAME = N'Store_log', FILENAME = N'D:\DATABASE\Store_log.ldf' , SIZE = 8192KB ,MAXSIZE= UNLIMITED ,FILEGROWTH = 65536KB )
